# Generated by Django 5.0.1 on 2024-01-22 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='link',
            field=models.TextField(blank=True, null=True, verbose_name='ссылка'),
        ),
    ]
